# Generated by Django 4.2.11 on 2025-03-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='imagen',
        ),
    ]
