# Generated by Django 4.2.11 on 2025-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_imagen_remove_equipo_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='nombre_imagen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre_imagen',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre_imagen',
            field=models.CharField(default='', max_length=30),
        ),
    ]
