# Generated by Django 4.2.11 on 2025-04-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_nombre_imagen_equipo_nombre_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='informacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='otros',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
