# Generated by Django 4.2.11 on 2025-04-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evento_informacion_evento_otros_evento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
